apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-wordpress-cm-1
  namespace: wordpress
data:
  wordpress-htaccess.conf: |
    php_value upload_max_filesize 256M
    php_value post_max_size 256M
    php_value max_execution_time 600
    php_value max_input_vars 2004
    php_value memory_limit 256M